#!/bin/bash

echo "🚀 Migrando MedCheck de Railway para Render..."
echo ""

echo "📋 INSTRUÇÕES PARA MIGRAÇÃO:"
echo ""
echo "1. 🌐 Acesse: https://render.com/"
echo "2. 🔐 Faça login com GitHub"
echo "3. ➕ Click 'New +' → 'Web Service'"
echo "4. 🔗 Conecte este repositório: https://github.com/assislucian/medcheck-app"
echo "5. ⚙️  Configure:"
echo "   Name: medcheck-backend"
echo "   Environment: Python 3"
echo "   Build Command: pip install -r requirements.txt"
echo "   Start Command: uvicorn src.main:app --host 0.0.0.0 --port \$PORT"
echo "   Health Check Path: /health"
echo ""
echo "6. 🔧 Adicione variáveis de ambiente:"
echo "   ENV=production"
echo "   ADMIN_SECRET=bQ7nP4yZrS1wV8kC5mT2xA9dL3fH6gJ0"
echo "   JWT_SECRET=bQ7nP4yZrS1wV8kC5mT2xA9dL3fH6gJ0"
echo "   FRONTEND_ORIGINS=https://medcheck-app.vercel.app,https://medcheck-app-assislucians-projects.vercel.app"
echo "   FRONTEND_ORIGIN_REGEX=https://medcheck-app-[a-z0-9-]+-assislucians-projects\.vercel\.app"
echo ""
echo "7. 🗄️  Adicione PostgreSQL:"
echo "   New + → PostgreSQL"
echo "   Name: medcheck-db"
echo "   Copie a DATABASE_URL e adicione nas env vars do web service"
echo ""
echo "8. 🚀 Deploy!"
echo ""
echo "🔄 APÓS DEPLOY NO RENDER:"
echo "1. Atualize VITE_API_URL no Vercel para nova URL do Render"
echo "2. Teste: curl https://[render-url]/health"
echo "3. Teste login no frontend"
echo ""
echo "✅ Render é muito mais estável que Railway para FastAPI"
echo "⚡ Deploy será mais rápido e confiável"
echo ""

# Opcional: teste se pode acessar Render
echo "🧪 Testando conectividade com Render..."
if curl -s --head https://render.com > /dev/null; then
    echo "✅ Render acessível"
else  
    echo "❌ Problema de conectividade"
fi

echo ""
echo "🎯 RESULTADO ESPERADO:"
echo "✅ Health endpoint: 200 OK"
echo "✅ CORS funcionando"
echo "✅ Frontend conectando sem erros"
echo "✅ Login funcionando end-to-end" 